### PR TITLE
[constraint-layout] Bump package to 2.0.0-alpha2 and add motionlayout fixup

### PR DESCRIPTION
**Pull request by garuma**
### Support Libraries Version (eg: 23.3.0)

same as master, only constraint-layout is updated

### Does this change any of the generated binding API's?

Yes

### Describe your contribution

Generate a constraint-layout nuget referencing the current alpha of `ConstraintLayout` which also brings a preview of `MotionLayout`.

### CODE REVIEW

**Comment by garuma** [comment]
@Redth fyi we were thinking of using this to demo basic `ConstraintLayout` support in the designer (via `MotionLayout` specifically) during the dev16 P2 timeframe. Still plenty of time to get around to it but I figured I would mention it :-) .

**Comment by Redth** [comment]
@garuma yup we've actually moved these bindings here: https://github.com/xamarin/XamarinComponents/tree/master/Android/ConstraintLayout but @newky2k will be working on a PR there today or tomorrow with your changes.  Thanks :)  Should have this out shortly!

**Comment by garuma** [comment]
middleparrot

**Comment by Redth** [comment]
Closing as we are tracking in https://github.com/xamarin/XamarinComponents/issues/484

**Pull request closed without merging**
